
project_id = "wxmxtdsoogozosaautvo"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.process-resume]
verify_jwt = false

[functions.process-job-match]
verify_jwt = false

[functions.process-learning-courses]
verify_jwt = false

[functions.create-resume-bucket]
verify_jwt = false
