// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxmxtdsoogozosaautvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bXh0ZHNvb2dvem9zYWF1dHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NzI5MzAsImV4cCI6MjA1MzA0ODkzMH0.X0wffrhiDsiE706jYpCJhvZjXSiBqVXvHoG7XilQXdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);